
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: oopsaccount/auth:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: green-peace
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: LoadBalancer
  selector:
    app: auth
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31333
