apiVersion: v1
data:
  BUCKET_HANDLER_SERVICE: bucket-handler-service
  BUCKET_HANDLER_PORT: "5165"
  BACKEND_SERVICE_PORT: "5600"
  SOLVER_MANAGER_SERVICE: solver-manager-service
  SOLVER_MANAGER_PORT: "8080"
  DATABASE_SERVICE: database-service
  DATABASE_PORT: "8080"
  DB_USER: dbmanager
  DB_PASS: Yc67i?\&7U"_yqO@
  DB_NAME: oopsdb
  CONNECTION_NAME: soptical-empire-364322:europe-west1:oopssql
  AUTH_SERVICE: auth-service
  AUTH_PORT: "3000"
  REACT_APP_AUTH_SERVICE: auth-service
  REACT_APP_AUTH_PORT: "3000"
  REACT_APP_DATABASE_SERVICE: database-service
  REACT_APP_DATABASE_PORT: "8080"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: green-peace
