apiVersion: apps/v1
kind: Deployment
metadata:
  name: solver-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solver-manager
  template:
    metadata:
      labels:
        app: solver-manager
    spec:
      containers:
        - name: solver-manager
          image: oopsaccount/solver-manager:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: green-peace
      serviceAccountName: solvermanager
---
apiVersion: v1
kind: Service
metadata:
  name: solver-manager-service
spec:
  selector:
    app: solver-manager
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
---

