apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlquery
  labels:
    app: sqlquery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlquery
  template:
    metadata:
      labels:
        app: sqlquery
    spec:
      containers:
        - name: sqlquery
          image: oopsaccount/sqlquery:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: green-peace
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: sqlquery
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31420
