apiVersion: apps/v1
kind: Deployment
metadata:
  name: solver-manager
spec:
  selector:
    matchLabels:
      app: solver-manager
  template:
    metadata:
      labels:
        app: solver-manager
    spec:
      containers:
        - name: solver-manager
          image: oops/solver-manager
          ports:
            - containerPort: 8080
