apiVersion: apps/v1
kind: Deployment
metadata:
  name: solver-manager
spec:
  selector:
    matchLabels:
      app: solver-manager
  template:
    metadata:
      labels:
        app: solver-manager
    spec:
      containers:
        - name: solver-manager
          image: oopsaccount/solver-manager:latest
          resources:
            limits:
              memory: "500MI"
              cpu: "500m"
          ports:
            - containerPort: 8080
