# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy Authentication Service To GKE

on:
  push:
    branches:
      - main
    paths:
      - Authentication/**
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: public-cluster
  GKE_ZONE: europe-north1-a    # Add your cluster zone here.
  
jobs:
  deploy-buckethandler:
    name: Apply Auth Deployment
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Wait for Auth image to build
      uses: lewagon/wait-on-check-action@v1.2.0
      with:
        ref: ${{ github.ref }}
        check-name: 'Build Auth'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
        
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    
    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
        
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: kubectl patch deployment auth -p \ "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"

