
name: Build and push BucketHandler to docker hub
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Execute kubectl command
        uses: actions-hub/kubectl@master
        with:
          context: ./Deployments
          args: create configmap green-peace --from-file=Environment
