
name: Create Config Map file (green-peace)
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Execute kubectl command
        working-directory: Deployments
        run: kubectl create configmap green-peace --from-file=environment
