name: Backend tests

on:
  push:
    branches:
      - feature/ln/backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build
        working-directory: ./Backend
        run: mvn --batch-mode -DskipTests package

      - name: Test
        working-directory: ./Backend
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
